# Generated by Django 4.1.13 on 2024-08-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootInsight',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('photoUrl', models.URLField()),
                ('Best_Position', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Stamina', models.IntegerField()),
                ('Strength', models.IntegerField()),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Agility', models.IntegerField()),
                ('Acceleration', models.IntegerField()),
                ('Sprint_Speed', models.IntegerField()),
                ('Nationality', models.CharField(max_length=255)),
                ('Club', models.CharField(max_length=255)),
                ('Cardiac_Frequency', models.IntegerField()),
                ('Humidity', models.IntegerField()),
                ('Temperature', models.IntegerField()),
                ('Status', models.CharField(max_length=50)),
                ('status_encoded', models.IntegerField()),
            ],
            options={
                'db_table': 'FootInsights',
            },
        ),
    ]
